steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/friendface/friendface:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/friendface/friendface:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', '$PROJECT_ID', '--region=europe-southwest1', '--image=europe-southwest1-docker.pkg.dev/$PROJECT_ID/friendface/frindface:$SHORT_SHA', '--update-env-vars', 'DOTENV_PATH=/etc/secrets/secrets_file', '--update-secrets=/etc/secrets/secrets_file=ENV_VARS:latest', '--add-cloudsql-instances=${PROJECT_ID}:europe-southwest1:frindface', '--allow-unauthenticated']
